
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 21 19:06:41 CST 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tcomillasimple = 22;
  public static final int cadena = 20;
  public static final int coma = 13;
  public static final int tsaltodelinea = 23;
  public static final int abrirllaves = 4;
  public static final int ERROR = 2;
  public static final int porcentaje = 8;
  public static final int conj = 3;
  public static final int comillas = 11;
  public static final int caracter = 19;
  public static final int guion = 24;
  public static final int disyuncion = 15;
  public static final int menorque = 9;
  public static final int cerrarllaves = 5;
  public static final int EOF = 0;
  public static final int mayorque = 10;
  public static final int error = 1;
  public static final int asterisco = 17;
  public static final int tilde = 12;
  public static final int interrogacion = 18;
  public static final int mas = 16;
  public static final int concatenacion = 14;
  public static final int dospuntos = 6;
  public static final int puntoycoma = 7;
  public static final int identificador = 21;
}

