
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 05 22:41:24 CST 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 21;
  public static final int coma = 14;
  public static final int abrirllaves = 4;
  public static final int ERROR = 2;
  public static final int porcentaje = 8;
  public static final int conj = 3;
  public static final int comillas = 12;
  public static final int caracter = 20;
  public static final int guion = 9;
  public static final int disyuncion = 16;
  public static final int menorque = 10;
  public static final int cerrarllaves = 5;
  public static final int EOF = 0;
  public static final int mayorque = 11;
  public static final int error = 1;
  public static final int asterisco = 18;
  public static final int tilde = 13;
  public static final int interrogacion = 19;
  public static final int mas = 17;
  public static final int concatenacion = 15;
  public static final int dospuntos = 6;
  public static final int puntoycoma = 7;
  public static final int identificador = 22;
}

